[workspace]
name = "pyfai-dioptas"
version = "0.1.0"
description = "Environment for pyFAI and Dioptas."
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = ">=3.10"
ipython = "*"
psutil = "==5.9.8"
qtawesome = "*"
jupyterlab = "*"
#matplotlib = "*"
numpy = ">=1.26.0,<2.0.0"
#pandas = "==2.1.1"
pillow = "*"
#scipy = "*"
ipympl = "*"
pyqt = "*"
pyfai-base = "==2025.3.0"
hdf5plugin = ">=5.0.0,<6.0.0"

[pypi-dependencies]
dioptas = "*"

[tasks]
ipython = "ipython"
lab = "jupyter lab"
pyfai = "pyFAI-calib2"
dioptas = "dioptas"

[target.osx.tasks]
#pyfai = '''
#python -c "
#import os
#import PyQt5
#os.environ['QT_API'] = 'PyQt5'

#from dioptas import main
#main()
#"
#'''

[environments]
terminal = { features = [], solve-group = "default" }

[activation.env]
QT_API = "PyQt5"